### ISSUE TITLE
Dollar sign may be not convenient

### ISSUE THREAD

**Issue by chang-zhao** [hafron/dokuwiki-plugin-proza#2] opened 2016-03-18 07:19 UTC
If I write $5 in a page text, it gets processed by Proza plugin as a link. In a future, if that plugin will be used by people, it may be inconvenient for them.

**Comment by hafron** [comment] 2017-01-29 15:50
Project PROZA is now merged with BEZ where the problem is already fixed.

**Closed by hafron** 2017-01-29 15:50 UTC
